export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_STAFFS = 'ADD_STAFFS';

export const ADD_STAFF = 'ADD_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';

export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';

export const STAFFSSALARY_LOADING = 'STAFFSSALARY_LOADING';
export const STAFFSSALARY_FAILED = 'STAFFSSALARY_FAILED';
export const ADD_STAFFSSALARY = 'ADD_STAFFSSALARY';